### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ismaelcig** [ismaelcig/TPV#1]
- [ ] Facilitar división de factura (cada uno paga lo suyo) añadiendo al DataGrid un checkBox para poder seleccionar qué cobrar
- [ ] Eliminar Tarjetas Descuento (dejar descuento de productos individuales)
- [ ] Categorías con subcategorías
- [ ] Mejora gráfica general
- [ ] Permitir imprimir factura
- [ ] Cambiar método de búsqueda Productos
- [ ] Manual de Usuario y documentación(?)
